-- ============================================================
-- AdSpy snapshot / historical intelligence storage
-- ============================================================

CREATE TABLE IF NOT EXISTS public.adspy_snapshots (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  user_id UUID NOT NULL
    REFERENCES auth.users(id)
    ON DELETE CASCADE,

  query TEXT NOT NULL,

  country TEXT NOT NULL DEFAULT 'IN',

  platform TEXT NOT NULL
    CHECK (platform IN ('meta', 'google', 'linkedin')),

  -- Complete ranked AdSpy result set.
  -- This intentionally stores the full result set, not only
  -- the 20 ads displayed on the current page.
  ads JSONB NOT NULL DEFAULT '[]'::jsonb,

  -- Intelligence summary generated by the AdSpy pipeline.
  intelligence JSONB NOT NULL DEFAULT '{}'::jsonb,

  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX IF NOT EXISTS adspy_snapshots_user_created_idx
ON public.adspy_snapshots(user_id, created_at DESC);

CREATE INDEX IF NOT EXISTS adspy_snapshots_user_query_idx
ON public.adspy_snapshots(user_id, query);

CREATE INDEX IF NOT EXISTS adspy_snapshots_user_country_idx
ON public.adspy_snapshots(user_id, country);

CREATE INDEX IF NOT EXISTS adspy_snapshots_user_platform_idx
ON public.adspy_snapshots(user_id, platform);

-- Useful for future historical intelligence queries.
CREATE INDEX IF NOT EXISTS adspy_snapshots_created_idx
ON public.adspy_snapshots(created_at DESC);

-- ============================================================
-- Row Level Security
-- ============================================================

ALTER TABLE public.adspy_snapshots ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- SELECT
-- ============================================================

DROP POLICY IF EXISTS "users can view their AdSpy snapshots"
ON public.adspy_snapshots;

CREATE POLICY "users can view their AdSpy snapshots"
ON public.adspy_snapshots
FOR SELECT
TO authenticated
USING (auth.uid() = user_id);

-- ============================================================
-- INSERT
-- ============================================================

DROP POLICY IF EXISTS "users can insert their AdSpy snapshots"
ON public.adspy_snapshots;

CREATE POLICY "users can insert their AdSpy snapshots"
ON public.adspy_snapshots
FOR INSERT
TO authenticated
WITH CHECK (auth.uid() = user_id);

-- ============================================================
-- DELETE
-- ============================================================

DROP POLICY IF EXISTS "users can delete their AdSpy snapshots"
ON public.adspy_snapshots;

CREATE POLICY "users can delete their AdSpy snapshots"
ON public.adspy_snapshots
FOR DELETE
TO authenticated
USING (auth.uid() = user_id);
