export type SeoSection = "commercial" | "guide" | "tool" | "industry" | "research";
export type CalculatorType = "roas" | "break-even-roas" | "cac" | "contribution-margin" | "rto";

export type SeoEntry = {
  section: SeoSection;
  slug: string;
  title: string;
  description: string;
  h1: string;
  eyebrow: string;
  intro: string;
  audience: string;
  focus: string[];
  caveat: string;
  related: string[];
  faqs: Array<{ q: string; a: string }>;
  calculator?: CalculatorType;
};

type Seed = Omit<SeoEntry, "section" | "eyebrow">;

function seed(section: SeoSection, s: Seed): SeoEntry {
  return { ...s, section, eyebrow: section === "commercial" ? "COMPETITOR AD INTELLIGENCE" : section === "guide" ? "D2C RESEARCH GUIDE" : section === "tool" ? "D2C TOOLS" : section === "industry" ? "D2C INDUSTRY RESEARCH" : "ZOOPTRACK RESEARCH" };
}

const commercialData: Seed[] = [
  {slug:"competitor-ad-intelligence",title:"Competitor Ad Intelligence for D2C",description:"Track competitor ads, creative changes, offers, formats and research history in one workflow.",h1:"Competitor ad intelligence for D2C",intro:"Turn competitor ad research into a repeatable operating system instead of a folder full of screenshots.",audience:"D2C founders, growth teams and agencies",focus:["Competitor discovery","Creative history","Offer and format analysis"],caveat:"Public ad libraries do not reveal a competitor's private profit, spend, ROAS or internal decision-making.",related:["/competitor-ad-research","/d2c-competitor-analysis","/guides/how-to-analyze-competitor-ads"],faqs:[{q:"What is competitor ad intelligence?",a:"A structured way to collect, normalize and compare competitor advertising evidence over time."},{q:"Can ad intelligence prove a winning ad?",a:"No. It can surface persistence and repeated creative patterns, but performance still requires your own testing data."}]},
  {slug:"competitor-ad-research",title:"Competitor Ad Research for D2C Brands",description:"A practical system for finding competitor ads, organizing evidence and turning observations into decisions.",h1:"Competitor ad research for D2C",intro:"Research competitor advertising without living inside an ad library all day.",audience:"Founders, marketers and competitive-intelligence teams",focus:["Search and identity resolution","Historical comparison","Evidence-led notes"],caveat:"Research becomes misleading when assumptions about spend, targeting or performance are presented as facts.",related:["/competitor-ad-intelligence","/meta-ad-library-competitor-research","/guides/how-to-find-competitor-ads"],faqs:[{q:"What should competitor ad research include?",a:"At minimum: advertiser identity, creative, copy, format, timing and the research question being tested."},{q:"How often should a team revisit the research?",a:"Use a cadence that matches how quickly your category changes; the goal is consistent comparison, not constant browsing."}]},
  {slug:"d2c-competitor-analysis",title:"D2C Competitor Analysis Using Advertising Evidence",description:"Compare competitor messaging, offers, formats and creative changes without pretending public ads reveal private business results.",h1:"D2C competitor analysis",intro:"Compare the moves you can actually observe, then separate facts from hypotheses.",audience:"D2C strategy, growth and brand teams",focus:["Competitor message map","Offer comparison","Creative pattern review"],caveat:"Do not turn public ad observations into unsupported claims about revenue, spend or campaign performance.",related:["/competitor-ad-intelligence","/industries/beauty","/industries/skincare"],faqs:[{q:"What makes D2C competitor analysis useful?",a:"A clear framework: the same dimensions, the same time window and explicit evidence for each observation."},{q:"Can ad analysis replace market research?",a:"No. It is one input into a broader research process that can include customers, pricing, product and channel data."}]},
  {slug:"d2c-ad-intelligence",title:"D2C Ad Intelligence Platform",description:"A public-ad evidence workflow for D2C teams that need to monitor competitors and build creative context.",h1:"D2C ad intelligence",intro:"Build memory around the ads your market keeps running.",audience:"D2C operators and performance marketing teams",focus:["Ad monitoring","Creative memory","Decision briefs"],caveat:"Zooptrack is not a private analytics source for competitors; it works from observable advertising evidence.",related:["/competitor-ad-intelligence","/guides/how-to-monitor-competitor-ads","/research/d2c-competitor-ad-trends"],faqs:[{q:"What is D2C ad intelligence?",a:"The organized collection and analysis of advertising signals that are publicly observable for D2C brands."},{q:"Who is it for?",a:"Teams that repeatedly research competitors and want a searchable, time-aware record rather than one-off screenshots."}]},
  {slug:"ad-spy-for-d2c",title:"Ad Spy for D2C Brands",description:"Use public competitor ads as research evidence, with context for hooks, offers, formats and creative history.",h1:"Ad spy for D2C brands",intro:"Use ad spying for research—not guesswork.",audience:"Performance marketers, founders and creative teams",focus:["Competitor discovery","Creative references","Offer monitoring"],caveat:"Ad spying cannot establish a competitor's spend, audience targeting, conversion rate or profitability from the public ad alone.",related:["/competitor-ad-research","/meta-ad-library","/guides/how-to-find-winning-ad-creatives"],faqs:[{q:"Is an ad spy tool a replacement for Meta Ad Library?",a:"No. Zooptrack is designed to make repeated competitor research faster and more structured around public ad-library evidence."},{q:"What should I save from a competitor ad?",a:"Save the creative, copy, offer, observed format, advertiser identity and the date you reviewed it."}]},
  {slug:"meta-ad-library-competitor-research",title:"Meta Ad Library Competitor Research",description:"A research workflow for using Meta's public advertising library as a source for competitor analysis.",h1:"Meta Ad Library competitor research",intro:"Make Meta Ad Library research systematic.",audience:"D2C marketers researching Facebook and Instagram competitors",focus:["Advertiser identity","Creative inspection","Historical context"],caveat:"Public ads are not a substitute for first-party campaign performance or private commercial data.",related:["/meta-ad-library","/facebook-ad-library","/instagram-ad-library","/guides/how-to-use-meta-ad-library"],faqs:[{q:"What can Meta Ad Library research tell me?",a:"It can help you study visible ad creative, copy and other public information returned by the library."},{q:"What can it not tell me?",a:"It cannot, by itself, validate a competitor's ROAS, spend, margin or conversion rate."}]},
  {slug:"meta-ad-library",title:"Meta Ad Library Research for D2C",description:"Understand how to use Meta's public ad library for competitor research, creative discovery and market monitoring.",h1:"Meta Ad Library",intro:"A practical starting point for competitor ad research.",audience:"Marketers, founders and analysts",focus:["Search strategy","Creative inspection","Repeatable research notes"],caveat:"Do not infer hidden business metrics from visible creative alone.",related:["/meta-ad-library-competitor-research","/facebook-ad-library","/instagram-ad-library"],faqs:[{q:"How should I start Meta Ad Library research?",a:"Start with one competitor and one concrete question, such as which offers or formats they are currently testing."},{q:"Why use a separate research workflow?",a:"Repeated competitive research benefits from history, consistent tagging and a clear record of what changed."}]},
  {slug:"facebook-ad-library",title:"Facebook Ad Library Research for Brands",description:"Research competitor Facebook ads, messaging and offers from public advertising evidence.",h1:"Facebook Ad Library research",intro:"Study Facebook ads with a repeatable research method.",audience:"D2C marketers and creative strategists",focus:["Facebook creative","Copy and offers","Competitor comparisons"],caveat:"Public ad evidence does not establish spend, targeting or campaign results.",related:["/meta-ad-library","/instagram-ad-library","/guides/facebook-ad-library-research"],faqs:[{q:"What should I look for in a Facebook ad?",a:"Look at the first promise, offer, proof, creative format, CTA and the context around when it was observed."},{q:"Can I use Facebook ads for creative research?",a:"Yes, as reference material and evidence of what a competitor is publicly communicating."}]},
  {slug:"instagram-ad-library",title:"Instagram Ad Library Research for Brands",description:"Use public Instagram advertising examples to study visual hooks, offers and messaging patterns.",h1:"Instagram Ad Library research",intro:"Research the creative language of Instagram ads.",audience:"D2C creative, content and growth teams",focus:["Visual hooks","Offer framing","Format comparison"],caveat:"A public Instagram ad does not provide private performance data for the competitor.",related:["/meta-ad-library","/facebook-ad-library","/guides/instagram-ad-research"],faqs:[{q:"What is useful in Instagram ad research?",a:"Visual structure, product framing, offer presentation, proof, CTA and how those elements repeat across creatives."},{q:"Should I copy a competitor creative?",a:"Use competitor ads as research evidence and inspiration; validate your own positioning and creative through original work and testing."}]},
  {slug:"meta-ad-library-india",title:"Meta Ad Library India for D2C Research",description:"A focused workflow for researching Indian D2C competitors through public Meta ad evidence.",h1:"Meta Ad Library India",intro:"Research Indian D2C advertising with consistent evidence.",audience:"India-focused D2C and agency teams",focus:["Indian advertiser research","Language and localization","Offer comparison"],caveat:"Do not convert public ad observations into unsupported claims about private business performance.",related:["/competitor-ad-intelligence","/industries/beauty","/industries/fashion","/research/india-d2c-advertising-report-2026"],faqs:[{q:"Why focus on India?",a:"A focused market scope makes competitor research easier to organize around local brands, language and category context."},{q:"Does Zooptrack estimate competitor ad spend?",a:"No. The public ad record is treated as evidence of advertising activity, not as proof of spend or results."}]}
];

const guideData: Seed[] = [
  {slug:"how-to-use-meta-ad-library",title:"How to Use Meta Ad Library for Competitor Research",description:"Learn a repeatable process for searching, checking advertiser identity, capturing evidence and comparing competitor ads.",h1:"How to use Meta Ad Library",intro:"Move from random searching to a defined research workflow.",audience:"Marketers starting competitor research",focus:["Search by advertiser","Check evidence","Save context"],caveat:"Do not infer hidden performance metrics from the ad itself.",related:["/meta-ad-library","/guides/how-to-find-competitor-ads"],faqs:[{q:"How long should a research session be?",a:"Long enough to answer the question you started with; a narrow question usually produces a more useful result than browsing indefinitely."},{q:"What makes the workflow repeatable?",a:"The same search, evidence fields, naming and comparison process every time."}]},
  {slug:"how-to-find-competitor-ads",title:"How to Find Competitor Ads",description:"A step-by-step workflow for identifying competitors and locating the right public advertising records.",h1:"How to find competitor ads",intro:"Find the right advertiser before you analyze the ad.",audience:"D2C founders and marketers",focus:["Competitor list","Advertiser matching","Creative capture"],caveat:"Do not assume every similar brand name is the correct advertiser.",related:["/competitor-ad-research","/meta-ad-library-competitor-research","/meta-ad-library"],faqs:[{q:"How many competitors should I start with?",a:"Start with a manageable set that represents the segment you actually compete in, then expand once the process is stable."},{q:"What if a brand has multiple advertiser pages?",a:"Verify which page matches the business you are researching before treating its ads as comparable evidence."}]},
  {slug:"how-to-analyze-competitor-ads",title:"How to Analyze Competitor Ads",description:"Break competitor ads into hooks, offers, proof, format, language and timing so your notes become actionable.",h1:"How to analyze competitor ads",intro:"Deconstruct the ad before you decide what it means.",audience:"Growth marketers and creative teams",focus:["Hook analysis","Offer analysis","Format and language"],caveat:"Analysis should produce hypotheses for your own testing, not certainty about a competitor's internal performance.",related:["/competitor-ad-intelligence","/guides/how-to-find-winning-ad-creatives","/d2c-competitor-analysis"],faqs:[{q:"What is the first thing to analyze?",a:"Start with the opening hook and main promise, then work through offer, proof, format and CTA."},{q:"How many ads are enough to see a pattern?",a:"There is no universal number; look for repetition across a meaningful sample and time window."}]},
  {slug:"how-to-monitor-competitor-ads",title:"How to Monitor Competitor Ads",description:"Set up a practical monitoring cadence for launches, persistent creatives and offer changes.",h1:"How to monitor competitor ads",intro:"Monitor the changes that can affect your next decision.",audience:"D2C marketing and strategy teams",focus:["Change detection","Launch tracking","Offer monitoring"],caveat:"Monitoring is only useful when the team knows what action a signal could change.",related:["/competitor-ad-intelligence","/d2c-ad-intelligence","/guides/how-to-monitor-competitor-offers"],faqs:[{q:"How often should I monitor competitors?",a:"Match the cadence to the category and the cost of missing a meaningful launch or offer change."},{q:"What should a monitoring note contain?",a:"What changed, when it changed, the evidence, why it may matter and what the team should verify next."}]},
  {slug:"how-to-research-d2c-competitors",title:"How to Research D2C Competitors",description:"Build a lightweight competitor-research system spanning advertising, offers, positioning and creative memory.",h1:"How to research D2C competitors",intro:"Turn competitor research into an operating habit.",audience:"D2C founders and strategy teams",focus:["Competitor map","Ad evidence","Decision notes"],caveat:"Competitor research is stronger when advertising evidence is combined with first-party market and customer information.",related:["/d2c-competitor-analysis","/competitor-ad-research","/research/d2c-competitor-ad-trends"],faqs:[{q:"What should a D2C competitor-research system include?",a:"A competitor list, repeatable questions, evidence capture, historical notes and an owner for each follow-up."},{q:"Why keep history?",a:"History turns isolated screenshots into a timeline that can be reviewed when your own strategy changes."}]},
  {slug:"meta-ad-library-for-d2c",title:"Meta Ad Library for D2C Brands",description:"Use public Meta advertising evidence to research competitors, discover creative ideas and monitor changes.",h1:"Meta Ad Library for D2C",intro:"Make Meta Ad Library useful to a D2C operating rhythm.",audience:"D2C founders, marketers and agencies",focus:["Brand search","Creative review","Change tracking"],caveat:"Do not confuse observable creative activity with business performance.",related:["/meta-ad-library","/d2c-ad-intelligence","/guides/instagram-ad-research"],faqs:[{q:"Can a D2C team use Meta Ad Library weekly?",a:"Yes. A recurring workflow can make public ad research easier to review and compare."},{q:"What should the team do with the findings?",a:"Turn them into hypotheses, briefs and questions for your own testing and customer research."}]},
  {slug:"facebook-ad-library-research",title:"Facebook Ad Library Research Guide",description:"A structured method for studying Facebook competitor creatives, offers, copy and timing.",h1:"Facebook Ad Library research",intro:"Research Facebook ads without a spreadsheet maze.",audience:"Performance marketers and creative strategists",focus:["Creative capture","Copy analysis","Historical comparison"],caveat:"Keep private metrics and inferred targeting out of the factual layer of your notes.",related:["/facebook-ad-library","/meta-ad-library","/guides/how-to-analyze-competitor-ads"],faqs:[{q:"What fields should I record?",a:"At minimum: advertiser, creative, copy, format, observed date, offer and your research note."},{q:"Should I screenshot everything?",a:"Only what supports the research question; structured capture is easier to search and compare later."}]},
  {slug:"instagram-ad-research",title:"Instagram Ad Research Guide",description:"Study visual hooks, creative formats, offers and messaging patterns in competitor Instagram advertising.",h1:"Instagram ad research",intro:"Read the creative pattern, not just the pretty ad.",audience:"D2C creative and content teams",focus:["Visual hooks","Format patterns","Offer framing"],caveat:"Do not mistake aesthetic similarity for evidence of commercial success.",related:["/instagram-ad-library","/facebook-ad-library","/guides/how-to-find-winning-ad-creatives"],faqs:[{q:"What should I capture from an Instagram ad?",a:"The opening visual, promise, offer, proof, CTA and the context that matters to your research question."},{q:"How should teams use the research?",a:"Use it to generate original creative hypotheses and sharper briefs."}]},
  {slug:"how-to-find-winning-ad-creatives",title:"How to Find Durable Competitor Ad Creatives",description:"Use persistence, repetition and creative context as research signals without claiming that public ads prove performance.",h1:"How to find durable competitor creatives",intro:"Use persistence as a clue—not a verdict.",audience:"Creative strategists and D2C growth teams",focus:["Creative persistence","Repeated hooks","Hypothesis building"],caveat:"Only your own first-party results can establish whether a similar creative works for your business.",related:["/competitor-ad-intelligence","/guides/how-to-analyze-competitor-ads","/research/d2c-ad-creative-trends-2026"],faqs:[{q:"Does a long-running ad prove it is a winner?",a:"No. It is a useful research signal that may justify closer inspection, not proof of a competitor's performance."},{q:"What should I test after finding a durable creative?",a:"Test the underlying proposition or angle with original creative and your own audience."}]},
  {slug:"how-to-monitor-competitor-offers",title:"How to Monitor Competitor Offers",description:"Track discounting, bundles, guarantees and other visible offer mechanics without guessing margin or profitability.",h1:"How to monitor competitor offers",intro:"See offer movement clearly, then decide what deserves a response.",audience:"D2C founders and growth teams",focus:["Discounts","Bundles","Offer changes"],caveat:"Never infer profitability or unit economics from the public offer alone.",related:["/competitor-ad-research","/d2c-competitor-analysis","/tools/break-even-roas"],faqs:[{q:"What offers should I track?",a:"Discounts, bundles, gifts, guarantees, subscriptions, urgency language and other mechanics visible in the creative or related context."},{q:"Should I match a competitor discount?",a:"Use the observed offer as a market signal; your own economics and positioning should determine whether you respond."}]}
];

const industryData: Seed[] = [
  {slug:"beauty",title:"D2C Beauty Advertising Research",description:"Research competitor ads in beauty with attention to offers, visual hooks, routines, proof and product format.",h1:"D2C beauty ad intelligence",intro:"Compare beauty advertising through the signals you can actually observe.",audience:"Beauty founders, marketers and agencies",focus:["Offer framing","Visual hooks","Proof and routine messaging"],caveat:"Do not infer efficacy, medical outcomes or private performance from an ad creative.",related:["/competitor-ad-intelligence","/meta-ad-library-india","/guides/how-to-analyze-competitor-ads"],faqs:[{q:"Why make beauty a separate research view?",a:"Category-specific questions make competitor research more useful than a generic list of ads."},{q:"What should beauty teams track?",a:"Proposition, routine, proof, offer, format, language and how those themes change over time."}]},
  {slug:"skincare",title:"D2C Skincare Ad Research",description:"A research framework for skincare brands to study offers, product routines, claims, proof and creative patterns.",h1:"D2C skincare ad intelligence",intro:"Study the messaging patterns shaping skincare advertising.",audience:"Skincare founders and marketing teams",focus:["Routine education","Claims and proof","Offer mechanics"],caveat:"Do not validate product efficacy or medical claims solely from competitor advertising.",related:["/competitor-ad-research","/meta-ad-library","/tools/break-even-roas"],faqs:[{q:"What is useful in skincare ad research?",a:"Look at product promise, routine, proof, offer and format while keeping factual observations separate from assumptions."},{q:"Can this support creative planning?",a:"Yes, as an input into hypothesis generation and competitive context."}]},
  {slug:"fashion",title:"D2C Fashion Ad Research",description:"Study competitor fashion advertising through product drops, styling hooks, offers, formats and visible localization.",h1:"D2C fashion ad intelligence",intro:"See how fashion competitors frame products and offers.",audience:"Fashion founders, marketers and agencies",focus:["Launches and drops","Styling hooks","Offer changes"],caveat:"Public competitor ads do not reveal inventory, sell-through, margin or private campaign performance.",related:["/d2c-ad-intelligence","/guides/instagram-ad-research","/meta-ad-library-india"],faqs:[{q:"What should fashion teams track?",a:"Drops, product focus, styling context, hooks, offers, formats and visible localization."},{q:"Can ad history help with launches?",a:"It can add context around how competitors communicate launches, but it does not reveal their internal inventory or sales plan."}]},
  {slug:"supplements",title:"D2C Supplements Ad Research",description:"A cautious research framework for supplement advertising, focused on offers, education, creative formats and observable claims.",h1:"D2C supplements ad intelligence",intro:"Research supplements advertising without turning claims into facts.",audience:"Supplement founders and growth teams",focus:["Education angles","Offers","Visible claims"],caveat:"Do not treat competitor claims as verified health outcomes.",related:["/competitor-ad-intelligence","/guides/how-to-analyze-competitor-ads","/research/d2c-ad-creative-trends-2026"],faqs:[{q:"What needs extra care in supplement research?",a:"Keep observations literal and separate from any conclusion about health outcomes or efficacy."},{q:"Can I use competitor supplements ads for creative research?",a:"Yes, as public creative and messaging references, while producing original and appropriately reviewed work."}]}
];

const researchData: Seed[] = [
  {slug:"india-d2c-advertising-report-2026",title:"India D2C Advertising Report 2026",description:"A methodology-led research page for studying Indian D2C advertising using public ad evidence without inventing market numbers.",h1:"India D2C Advertising Report 2026",intro:"A transparent research framework for Indian D2C advertising.",audience:"Teams studying Indian D2C competition",focus:["Market scope","Ad evidence","Research methodology"],caveat:"This page does not publish fabricated industry spend, ROAS or market-share numbers.",related:["/meta-ad-library-india","/research/d2c-ad-creative-trends-2026","/research/d2c-competitor-ad-trends"],faqs:[{q:"Is this a spend report?",a:"No. The research framework is built around public advertising evidence and avoids inventing private spend or performance metrics."},{q:"When should a benchmark be published?",a:"Only when the sample, collection window and calculation method are clear enough for another reader to understand what the number represents."}]},
  {slug:"d2c-ad-creative-trends-2026",title:"D2C Ad Creative Trends 2026",description:"A research methodology for identifying recurring creative patterns across D2C advertising without overstating what public ads prove.",h1:"D2C ad creative trends 2026",intro:"Track the creative patterns worth testing.",audience:"Creative strategists and growth teams",focus:["Hook taxonomy","Format taxonomy","Persistence signals"],caveat:"No trend should be presented as a universal winning formula without first-party testing.",related:["/guides/how-to-find-winning-ad-creatives","/research/d2c-competitor-ad-trends","/competitor-ad-intelligence"],faqs:[{q:"What counts as a trend?",a:"A repeatable pattern observed across a clearly defined sample and time window."},{q:"Will this page show current numbers?",a:"Only when the underlying sample and methodology are available; the page avoids placeholder statistics."}]},
  {slug:"d2c-offer-trends-2026",title:"D2C Offer Trends 2026",description:"Track observable discount, bundle, gift, urgency and guarantee mechanics across competitor advertising.",h1:"D2C offer trends 2026",intro:"Understand offer movement without guessing margins.",audience:"D2C founders and commercial teams",focus:["Offer taxonomy","Offer persistence","Category comparison"],caveat:"Do not infer a competitor's margin or willingness-to-pay from a visible discount alone.",related:["/guides/how-to-monitor-competitor-offers","/tools/break-even-roas","/research/india-d2c-advertising-report-2026"],faqs:[{q:"What offer types can be tracked?",a:"Discounts, bundles, gifts, guarantees, urgency and other mechanics visible in the creative or related context."},{q:"Why pair offer research with unit economics?",a:"Because an offer can be attractive to customers while still having very different economics for different businesses."}]},
  {slug:"meta-advertising-india-2026",title:"Meta Advertising India 2026",description:"A transparent research framework for studying Indian Meta advertising with clearly scoped public ad data.",h1:"Meta advertising India 2026",intro:"Research Indian Meta advertising with explicit scope.",audience:"Agencies, marketers and analysts",focus:["Market scope","Language and format","Methodology"],caveat:"No private spend or ROAS estimate is presented as fact on this research surface.",related:["/meta-ad-library-india","/research/india-d2c-advertising-report-2026","/meta-ad-library-competitor-research"],faqs:[{q:"What is the geographic scope?",a:"The research is framed around Indian advertising observations and must state its exact sample when a benchmark is published."},{q:"How is evidence handled?",a:"The source, collection window and calculation method are kept explicit so readers can understand the limits of each finding."}]},
  {slug:"d2c-competitor-ad-trends",title:"D2C Competitor Ad Trends",description:"A methodology page for tracking changes in competitor ad activity, offers and creative direction over time.",h1:"D2C competitor ad trends",intro:"Build memory around competitor advertising changes.",audience:"D2C strategy and growth teams",focus:["Change detection","Creative persistence","Offer movement"],caveat:"Competitor trend pages should never convert missing private data into confident numbers.",related:["/competitor-ad-intelligence","/guides/how-to-monitor-competitor-ads","/research/d2c-ad-creative-trends-2026"],faqs:[{q:"Why track trends instead of screenshots?",a:"A timeline makes it easier to understand what changed, what stayed and which questions are worth investigating."},{q:"What should a trend note contain?",a:"The observed change, source evidence, comparison window, why it may matter and what remains unknown."}]}
];

const tools: SeoEntry[] = [
  seed("tool",{slug:"roas-calculator",title:"ROAS Calculator",description:"Calculate return on ad spend from revenue and advertising spend.",h1:"ROAS calculator",intro:"Get the arithmetic right before you interpret the result.",audience:"Marketers and D2C operators",focus:["Revenue","Ad spend","ROAS"],caveat:"ROAS alone does not tell you contribution margin or profit.",related:["/tools/break-even-roas","/d2c-ad-intelligence"],faqs:[{q:"What is the formula?",a:"ROAS is revenue divided by advertising spend."},{q:"Does ROAS equal profit?",a:"No. Profit also depends on product economics and other costs."}],calculator:"roas"}),
  seed("tool",{slug:"break-even-roas",title:"Break-Even ROAS Calculator",description:"Calculate the ROAS at which contribution covers ad spend under a simple margin assumption.",h1:"Break-even ROAS calculator",intro:"Know the minimum ROAS your economics require.",audience:"D2C founders and performance marketers",focus:["Contribution margin","Break-even ROAS","Scenario thinking"],caveat:"The real break-even point depends on the exact costs included in your margin definition.",related:["/tools/roas-calculator","/guides/how-to-monitor-competitor-offers"],faqs:[{q:"What is the simplified formula?",a:"Break-even ROAS is 1 divided by contribution margin expressed as a decimal."},{q:"Is the result a forecast?",a:"No. It is a transparent guardrail based on your input assumptions."}],calculator:"break-even-roas"}),
  seed("tool",{slug:"cac-calculator",title:"CAC Calculator",description:"Calculate customer acquisition cost from acquisition spend and new customers.",h1:"CAC calculator",intro:"Turn acquisition spend into a comparable customer cost.",audience:"Growth teams and founders",focus:["Acquisition spend","New customers","CAC"],caveat:"A blended CAC can hide channel and cohort differences.",related:["/tools/contribution-margin","/competitor-ad-intelligence"],faqs:[{q:"What is the formula?",a:"CAC is acquisition spend divided by new customers acquired."},{q:"What should CAC be compared with?",a:"Compare it with contribution per customer, payback assumptions and cohort economics."}],calculator:"cac"}),
  seed("tool",{slug:"contribution-margin",title:"Contribution Margin Calculator",description:"Estimate contribution margin from revenue and variable costs with explicit inputs.",h1:"Contribution margin calculator",intro:"See what is left before fixed costs and advertising.",audience:"D2C finance and growth teams",focus:["Revenue","Variable costs","Contribution margin"],caveat:"The result is only as useful as the cost definition behind it.",related:["/tools/roas-calculator","/tools/break-even-roas"],faqs:[{q:"What is contribution margin?",a:"For this calculator, it is contribution profit divided by revenue using the variable costs you enter."},{q:"Why define the costs carefully?",a:"Different teams include different variable costs, so the definition needs to stay consistent across comparisons."}],calculator:"contribution-margin"}),
  seed("tool",{slug:"rto-calculator",title:"RTO Calculator",description:"Calculate return-to-origin rate from shipped orders and returned orders.",h1:"RTO calculator",intro:"Measure the return-to-origin rate clearly.",audience:"COD-heavy D2C teams and operators",focus:["Shipped orders","RTO orders","RTO rate"],caveat:"RTO rate alone does not measure the full financial impact of returns.",related:["/tools/contribution-margin","/industries/fashion"],faqs:[{q:"What is the formula?",a:"RTO rate is returned-to-origin orders divided by shipped orders."},{q:"What should I track alongside RTO?",a:"Track fulfillment cost, contribution margin, customer experience and the cohort definition used for the rate."}],calculator:"rto"})
];

export const commercialEntries = commercialData.map((s) => seed("commercial", s));
export const guideEntries = guideData.map((s) => seed("guide", s));
export const toolEntries = tools;
export const industryEntries = industryData.map((s) => seed("industry", s));
export const researchEntries = researchData.map((s) => seed("research", s));

export const allSeoEntries: SeoEntry[] = [...commercialEntries, ...guideEntries, ...toolEntries, ...industryEntries, ...researchEntries];
export function seoPath(entry: SeoEntry) {
  if (entry.section === "commercial") return `/${entry.slug}`;
  return `/${entry.section === "guide" ? "guides" : entry.section === "tool" ? "tools" : entry.section === "industry" ? "industries" : "research"}/${entry.slug}`;
}
export function findSeoEntry(section: SeoSection, slug: string) {
  return allSeoEntries.find((entry) => entry.section === section && entry.slug === slug) ?? null;
}
