const sections = [
  {
    title: "Information We Collect",
    body:
      "We collect account details (name, email, phone), workspace inputs you provide, and usage data needed to operate the Zooptrack Growth Intelligence Command Center."
  },
  {
    title: "How We Use Data",
    body:
      "We use your data to authenticate users, calculate reports, save scenarios and monthly records, and provide AI-backed insights. We do not sell personal data."
  },
  {
    title: "Data Storage",
    body:
      "Account profiles and workspace records are stored in our database. Insights generated by AI providers may be processed by third-party services when enabled."
  },
  {
    title: "Your Choices",
    body:
      "You can request access, corrections, or deletion of your data by contacting us. You can also sign out at any time to stop ongoing use."
  },
  {
    title: "Security",
    body:
      "We apply access controls, authentication, and database policies to protect your information. No method is 100% secure, but we work to protect your data."
  },
  {
    title: "Contact",
    body:
      "For privacy questions, contact support@yourcompany.com."
  }
];

export default function PrivacyPage() {
  return (
    <main className="main policy-page privacy-page">
      <header className="policy-hero">
        <p className="eyebrow">Legal</p>
        <h1>Privacy Policy</h1>
        <p className="muted-text">
          This policy explains how we collect, use, and safeguard information in the Zooptrack Growth Intelligence Command Center.
        </p>
        <p className="policy-meta">Effective date: March 10, 2026</p>
      </header>
      <section className="policy-grid">
        {sections.map((section) => (
          <article key={section.title} className="policy-card">
            <h3>{section.title}</h3>
            <p className="muted-text">{section.body}</p>
          </article>
        ))}
      </section>
    </main>
  );
}
